version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasker-bot
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB}
    command: sh -c "yarn sq db:migrate && yarn start"
