name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@77.232.138.71 << 'EOF'
            cd /var/www/tasker-bot
            git pull
            docker stop taskerbot || true
            docker rm taskerbot || true
            docker build --network=host -t tasker-bot .
            docker run -d --restart=always --name taskerbot --network=host -p 3000:3000 tasker-bot
          EOF
